apiVersion: v1  # Secret is for mongo-db database internal service request only.
kind: Secret    # So that only mongo-express application send request.
metadata:       # Internally kubernetes provide this facility.
  name: mongodb-secret
type: Opaque
data:
  username: dXNlcm5hbWU=
  password: cGFzc3dvcmQ=
